baseURL = "audryhsu.com"
languageCode = "en-us"
theme = "hugo-winston-theme"
themesDir = "themes"
title = "Audry Hsu"
paginate = 3
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  google_analytics_id = ""
#  twitter_handle = "@zerostaticio"
  showAuthorOnHomepage = true
  showAuthorOnPosts = false
  showIntroContentOnHomepage = true
  showPostsOnHomepage = false
  usePaginationOnHomepage = false
  limitPostsOnHomepage = 3 # only used if usePaginationOnHomepage is false
  sortPostsByDateOldestFirst = false
  addDot = true
  addFrame = true
  highlightColor = '#97C0D8' # border and links
  baseColor = "#FFFCF2" # background
  baseOffsetColor = "#eaeaea"
  headingColor = "#131B2A"
  textColor = "#131B2A"
  dotColor = "#F2A07D"
  enableGoogleFonts = true 
  googleFontsUrl = "https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap"
  fontFamilyHeading = "Poppins"
  fontFamilyParagraph = "Poppins"
  fontFamilyMonospace = "monospace"

# markdown config settings https://gohugo.io/getting-started/configuration-markup/#goldmark
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = 1
  [[menu.main]]
    name = "Blog"
    identifier = "blog"
    weight = 2
    url = "/posts/"
  [[menu.main]]
    name = "About"
    identifier = "about"
    weight = 3
    url = "/pages/about/"
  [[menu.main]]
    name = "Tags"
    identifier = "tags"
    weight = 4
    url = "/tags/"
[taxonomies]
  tag = "tags"
  category = "categories"
# add any custom taxonomies here so that Hugo will auto-create pages for them
  mood = "moods"

[deployment]
# files that match the regex will be uploaded first
order = [".jpg$", ".gif$", ".png$", ".svg$"]
  [[deployment.targets]]
    name = "GitHub"
    URL = ""

